name: AI Test Generation Pipeline

# Trigger on every push to 'main' branch (adjust as needed)
on:
  push:
    branches: ["main"]
  pull_request:          # <‑‑ new
    branches: ["main"]   # run when PR targets main
permissions:
  contents: write  # allow the workflow to create branches/PRs

jobs:
  generate_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # full history to compute diffs if needed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # or 3.11, as needed

      - name: Install dependencies
        run: pip install pytest openai

      - name: Generate unit tests with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/generate_tests.py

      - name: Run tests
        run: pytest -q  # run the test suite (generated tests + existing tests)

      - name: Create Pull Request with generated tests
        # Uses peter-evans/create-pull-request to commit changes and open a PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: add AI-generated tests [ci skip]"
          branch: ai-tests-${{ github.sha }}
          title: "Add AI-generated unit tests"
          body: "This PR adds unit tests generated by OpenAI for the latest changes."
