name: AI Test Generation Pipeline

on:
  push:
    branches: ["main"]        # adjust if your default branch is different

permissions:
  contents: write
  pull-requests: write        # ⬅ needed to open a PR

jobs:
  generate_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}    # ⬅ stay on the real branch (no detached HEAD)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest openai    # no version pin now that the script uses >=1.0

      - name: Generate unit tests with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/generate_tests.py

      - name: Run tests
        run: pytest -q

      - name: Create Pull Request with generated tests
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: add AI-generated tests [ci skip]"
          branch: ai-tests-${{ github.sha }}
          title: "Add AI-generated unit tests"
          body: "This PR adds unit tests generated by OpenAI for the latest changes."
          base: main                     # ⬅ explicit merge target
